//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyanka_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int id { get; set; }
        public int id_storehouse { get; set; }
        public int id_order { get; set; }
        public string FIO { get; set; }
        public int post { get; set; }
        public string gender { get; set; }
    
        public virtual Order_ Order_ { get; set; }
        public virtual Storehouse Storehouse { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
