//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyanka_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_in_storehouse
    {
        public int id { get; set; }
        public int id_Storehouse { get; set; }
        public string product_name { get; set; }
        public string unit { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Storehouse Storehouse { get; set; }
    }
}
